/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import Modelo.*;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_servTeclado = new javax.swing.JFrame();
        teclado_btn1 = new javax.swing.JButton();
        teclado_btn3 = new javax.swing.JButton();
        teclado_btn4 = new javax.swing.JButton();
        teclado_btn5 = new javax.swing.JButton();
        teclado_btn6 = new javax.swing.JButton();
        teclado_btn7 = new javax.swing.JButton();
        teclado_btn8 = new javax.swing.JButton();
        teclado_btn9 = new javax.swing.JButton();
        teclado_btnAceptar = new javax.swing.JButton();
        teclado_btn0 = new javax.swing.JButton();
        teclado_btnAtras = new javax.swing.JButton();
        teclado_btnLimpiar = new javax.swing.JButton();
        teclado_btn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_loginMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_loginPass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tBtn_tecladoMatricula = new javax.swing.JToggleButton();
        tBtn_tecladoPass = new javax.swing.JToggleButton();

        frame_servTeclado.setTitle("ServTeclado");
        frame_servTeclado.setMinimumSize(new java.awt.Dimension(250, 396));
        frame_servTeclado.setSize(new java.awt.Dimension(180, 230));

        teclado_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn1.setText("1");

        teclado_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn3.setText("3");
        teclado_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclado_btn3ActionPerformed(evt);
            }
        });

        teclado_btn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn4.setText("4");

        teclado_btn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn5.setText("5");

        teclado_btn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn6.setText("6");

        teclado_btn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn7.setText("7");

        teclado_btn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn8.setText("8");

        teclado_btn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn9.setText("9");

        teclado_btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnAceptar.setText("Aceptar");

        teclado_btn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn0.setText("0");

        teclado_btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnAtras.setText("«");

        teclado_btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnLimpiar.setText("C");

        teclado_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn2.setText("2");

        javax.swing.GroupLayout frame_servTecladoLayout = new javax.swing.GroupLayout(frame_servTeclado.getContentPane());
        frame_servTeclado.getContentPane().setLayout(frame_servTecladoLayout);
        frame_servTecladoLayout.setHorizontalGroup(
            frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addComponent(teclado_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teclado_btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(teclado_btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teclado_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                                .addComponent(teclado_btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teclado_btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addComponent(teclado_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teclado_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teclado_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(teclado_btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_servTecladoLayout.setVerticalGroup(
            frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teclado_btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teclado_btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teclado_btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teclado_btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CajeroUT");

        jLabel2.setText("Matrícula:");

        jLabel3.setText("Contraseña:");

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login36.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lobo_escudo.jpg"))); // NOI18N

        tBtn_tecladoMatricula.setText(" Teclado");

        tBtn_tecladoPass.setText(" Teclado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_loginMatricula)
                                    .addComponent(txt_loginPass))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tBtn_tecladoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(tBtn_tecladoPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_tecladoMatricula)
                            .addComponent(txt_loginMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_tecladoPass)
                            .addComponent(txt_loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_login)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teclado_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclado_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclado_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_login;
    public javax.swing.JFrame frame_servTeclado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JToggleButton tBtn_tecladoMatricula;
    public javax.swing.JToggleButton tBtn_tecladoPass;
    public javax.swing.JButton teclado_btn0;
    public javax.swing.JButton teclado_btn1;
    public javax.swing.JButton teclado_btn2;
    public javax.swing.JButton teclado_btn3;
    public javax.swing.JButton teclado_btn4;
    public javax.swing.JButton teclado_btn5;
    public javax.swing.JButton teclado_btn6;
    public javax.swing.JButton teclado_btn7;
    public javax.swing.JButton teclado_btn8;
    public javax.swing.JButton teclado_btn9;
    public javax.swing.JButton teclado_btnAceptar;
    public javax.swing.JButton teclado_btnAtras;
    public javax.swing.JButton teclado_btnLimpiar;
    public javax.swing.JTextField txt_loginMatricula;
    public javax.swing.JPasswordField txt_loginPass;
    // End of variables declaration//GEN-END:variables
}
