/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class principalMenu extends javax.swing.JFrame {

    /**
     * Creates new form principalMenu
     */
    public principalMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_usrSaudo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_servCaja = new javax.swing.JMenu();
        jMenuItem_servCaja = new javax.swing.JMenuItem();
        jMenuItem_servCreditoUT = new javax.swing.JMenuItem();
        jMenuItem_servLoboletos = new javax.swing.JMenuItem();
        jMenuItem_servEvaluacion = new javax.swing.JMenuItem();
        jMenuItem_servBuzon = new javax.swing.JMenuItem();
        jMenu_Consultas = new javax.swing.JMenu();
        jMenuItem_consCalificaciones = new javax.swing.JMenuItem();
        jMenuItem_consHorario = new javax.swing.JMenuItem();
        jMenuItem_consEdoCuenta = new javax.swing.JMenuItem();
        jMenuItem_ConsMapa = new javax.swing.JMenuItem();
        jMenuItem_calendario = new javax.swing.JMenuItem();
        jMenu_tramites = new javax.swing.JMenu();
        jMenuItem_becas = new javax.swing.JMenuItem();
        jMenuItem_constancias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_correo = new javax.swing.JMenuItem();
        jMenuItem_navega = new javax.swing.JMenuItem();
        jMenuItem_soporte = new javax.swing.JMenuItem();
        jMenu_cerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg_avion.png"))); // NOI18N

        lbl_usrSaudo.setText("Usr");

        jMenuBar1.setBackground(new java.awt.Color(6, 12, 60));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu_servCaja.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_servCaja.setText("Servicios");

        jMenuItem_servCaja.setText("Caja");
        jMenu_servCaja.add(jMenuItem_servCaja);

        jMenuItem_servCreditoUT.setText("CreditoUT");
        jMenu_servCaja.add(jMenuItem_servCreditoUT);

        jMenuItem_servLoboletos.setText("Loboletos");
        jMenu_servCaja.add(jMenuItem_servLoboletos);

        jMenuItem_servEvaluacion.setText("Evaluación de servicios");
        jMenu_servCaja.add(jMenuItem_servEvaluacion);

        jMenuItem_servBuzon.setText("Buzón de quejas y sugerencias");
        jMenu_servCaja.add(jMenuItem_servBuzon);

        jMenuBar1.add(jMenu_servCaja);

        jMenu_Consultas.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Consultas.setText("Consultas");

        jMenuItem_consCalificaciones.setText("Calificaciones");
        jMenu_Consultas.add(jMenuItem_consCalificaciones);

        jMenuItem_consHorario.setText("Horario");
        jMenu_Consultas.add(jMenuItem_consHorario);

        jMenuItem_consEdoCuenta.setText("Estado de cuenta");
        jMenu_Consultas.add(jMenuItem_consEdoCuenta);

        jMenuItem_ConsMapa.setText("Mapa Universidad");
        jMenu_Consultas.add(jMenuItem_ConsMapa);

        jMenuItem_calendario.setText("Calendario");
        jMenu_Consultas.add(jMenuItem_calendario);

        jMenuBar1.add(jMenu_Consultas);

        jMenu_tramites.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_tramites.setText("Trámites");

        jMenuItem_becas.setText("Becas");
        jMenu_tramites.add(jMenuItem_becas);

        jMenuItem_constancias.setText("Constancias");
        jMenu_tramites.add(jMenuItem_constancias);

        jMenuBar1.add(jMenu_tramites);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("LobosConect");

        jMenuItem_correo.setText("Correo");
        jMenu4.add(jMenuItem_correo);

        jMenuItem_navega.setText("Navegar");
        jMenu4.add(jMenuItem_navega);

        jMenuItem_soporte.setText("Soporte");
        jMenu4.add(jMenuItem_soporte);

        jMenuBar1.add(jMenu4);

        jMenu_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_cerrarSesion.setText("Cerrar sesión");
        jMenuBar1.add(jMenu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_usrSaudo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lbl_usrSaudo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem_ConsMapa;
    public javax.swing.JMenuItem jMenuItem_becas;
    public javax.swing.JMenuItem jMenuItem_calendario;
    public javax.swing.JMenuItem jMenuItem_consCalificaciones;
    public javax.swing.JMenuItem jMenuItem_consEdoCuenta;
    public javax.swing.JMenuItem jMenuItem_consHorario;
    public javax.swing.JMenuItem jMenuItem_constancias;
    public javax.swing.JMenuItem jMenuItem_correo;
    public javax.swing.JMenuItem jMenuItem_navega;
    public javax.swing.JMenuItem jMenuItem_servBuzon;
    public javax.swing.JMenuItem jMenuItem_servCaja;
    public javax.swing.JMenuItem jMenuItem_servCreditoUT;
    public javax.swing.JMenuItem jMenuItem_servEvaluacion;
    public javax.swing.JMenuItem jMenuItem_servLoboletos;
    public javax.swing.JMenuItem jMenuItem_soporte;
    public javax.swing.JMenu jMenu_Consultas;
    public javax.swing.JMenu jMenu_cerrarSesion;
    public javax.swing.JMenu jMenu_servCaja;
    public javax.swing.JMenu jMenu_tramites;
    public javax.swing.JLabel lbl_usrSaudo;
    // End of variables declaration//GEN-END:variables
}
