/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import Modelo.*;

/**
 *
 * @author Usuario
 */
public class servCaja extends javax.swing.JFrame {

    /**
     * Creates new form principalMenu
     */
    public servCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_servTeclado = new javax.swing.JFrame();
        teclado_btn1 = new javax.swing.JButton();
        teclado_btn3 = new javax.swing.JButton();
        teclado_btn4 = new javax.swing.JButton();
        teclado_btn5 = new javax.swing.JButton();
        teclado_btn6 = new javax.swing.JButton();
        teclado_btn7 = new javax.swing.JButton();
        teclado_btn8 = new javax.swing.JButton();
        teclado_btn9 = new javax.swing.JButton();
        teclado_btnAceptar = new javax.swing.JButton();
        teclado_btn0 = new javax.swing.JButton();
        teclado_btnAtras = new javax.swing.JButton();
        teclado_btnLimpiar = new javax.swing.JButton();
        teclado_btn2 = new javax.swing.JButton();
        radioGroup_formaPago = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cb_tipoPago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rd_pagoCreditoUT = new javax.swing.JRadioButton();
        rd_pagoTarjeta = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_numTarjeta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_vencimientoMes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_vencimientoAnio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pass_cve = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_recibo = new javax.swing.JTextArea();
        btn_pagar = new javax.swing.JButton();
        tBtn_tecladoTarjeta = new javax.swing.JToggleButton();
        tBtn_tecladoCVE = new javax.swing.JToggleButton();
        cb_tipoPago_loboleto = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_servCaja = new javax.swing.JMenu();
        jMenuItem_servCaja = new javax.swing.JMenuItem();
        jMenuItem_servCreditoUT = new javax.swing.JMenuItem();
        jMenuItem_servLoboletos = new javax.swing.JMenuItem();
        jMenuItem_servEvaluacion = new javax.swing.JMenuItem();
        jMenuItem_servBuzon = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_consCalificaciones = new javax.swing.JMenuItem();
        jMenuItem_consHorario = new javax.swing.JMenuItem();
        jMenuItem_consEdoCuenta = new javax.swing.JMenuItem();
        jMenuItem_ConsMapa = new javax.swing.JMenuItem();
        jMenuItem_calendario = new javax.swing.JMenuItem();
        jMenu_tramites = new javax.swing.JMenu();
        jMenuItem_becas = new javax.swing.JMenuItem();
        jMenuItem_constancias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_correo = new javax.swing.JMenuItem();
        jMenuItem_navega = new javax.swing.JMenuItem();
        jMenuItem_soporte = new javax.swing.JMenuItem();
        jMenu_cerrarSesion = new javax.swing.JMenu();

        frame_servTeclado.setTitle("ServTeclado");
        frame_servTeclado.setMinimumSize(new java.awt.Dimension(250, 396));

        teclado_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn1.setText("1");

        teclado_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn3.setText("3");
        teclado_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclado_btn3ActionPerformed(evt);
            }
        });

        teclado_btn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn4.setText("4");

        teclado_btn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn5.setText("5");

        teclado_btn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn6.setText("6");

        teclado_btn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn7.setText("7");

        teclado_btn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn8.setText("8");

        teclado_btn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn9.setText("9");

        teclado_btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnAceptar.setText("Aceptar");

        teclado_btn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn0.setText("0");

        teclado_btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnAtras.setText("«");

        teclado_btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btnLimpiar.setText("C");

        teclado_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teclado_btn2.setText("2");

        javax.swing.GroupLayout frame_servTecladoLayout = new javax.swing.GroupLayout(frame_servTeclado.getContentPane());
        frame_servTeclado.getContentPane().setLayout(frame_servTecladoLayout);
        frame_servTecladoLayout.setHorizontalGroup(
            frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addComponent(teclado_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teclado_btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(teclado_btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teclado_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                                .addComponent(teclado_btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teclado_btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frame_servTecladoLayout.createSequentialGroup()
                        .addComponent(teclado_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclado_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teclado_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teclado_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(teclado_btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        frame_servTecladoLayout.setVerticalGroup(
            frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclado_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclado_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teclado_btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_servTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teclado_btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teclado_btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teclado_btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de pago:");

        cb_tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colegiatura", "Examen", "Inscripción", "Titulación", "Loboletos" }));

        jLabel2.setText("Forma de pago:");

        radioGroup_formaPago.add(rd_pagoCreditoUT);
        rd_pagoCreditoUT.setSelected(true);
        rd_pagoCreditoUT.setText("CreditoUT");

        radioGroup_formaPago.add(rd_pagoTarjeta);
        rd_pagoTarjeta.setText("Tarjeta");

        jLabel3.setText("Número de tarjeta:");

        jLabel4.setText("Vencimiento:");

        cb_vencimientoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel5.setText("/");

        cb_vencimientoAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));

        jLabel6.setText("CVE:");

        txtArea_recibo.setColumns(20);
        txtArea_recibo.setRows(5);
        jScrollPane1.setViewportView(txtArea_recibo);

        btn_pagar.setText("Pagar");

        tBtn_tecladoTarjeta.setText("Teclado");

        tBtn_tecladoCVE.setText("Teclado");

        cb_tipoPago_loboleto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Lobobus", "Impresiones", "Copias" }));

        jMenuBar1.setBackground(new java.awt.Color(6, 12, 60));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu_servCaja.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_servCaja.setText("Servicios");

        jMenuItem_servCaja.setText("Caja");
        jMenu_servCaja.add(jMenuItem_servCaja);

        jMenuItem_servCreditoUT.setText("CreditoUT");
        jMenu_servCaja.add(jMenuItem_servCreditoUT);

        jMenuItem_servLoboletos.setText("Loboletos");
        jMenu_servCaja.add(jMenuItem_servLoboletos);

        jMenuItem_servEvaluacion.setText("Evaluación de servicios");
        jMenu_servCaja.add(jMenuItem_servEvaluacion);

        jMenuItem_servBuzon.setText("Buzón de quejas y sugerencias");
        jMenu_servCaja.add(jMenuItem_servBuzon);

        jMenuBar1.add(jMenu_servCaja);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Consultas");

        jMenuItem_consCalificaciones.setText("Calificaciones");
        jMenu2.add(jMenuItem_consCalificaciones);

        jMenuItem_consHorario.setText("Horario");
        jMenu2.add(jMenuItem_consHorario);

        jMenuItem_consEdoCuenta.setText("Estado de cuenta");
        jMenu2.add(jMenuItem_consEdoCuenta);

        jMenuItem_ConsMapa.setText("Mapa Universidad");
        jMenu2.add(jMenuItem_ConsMapa);

        jMenuItem_calendario.setText("Calendario");
        jMenu2.add(jMenuItem_calendario);

        jMenuBar1.add(jMenu2);

        jMenu_tramites.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_tramites.setText("Trámites");

        jMenuItem_becas.setText("Becas");
        jMenu_tramites.add(jMenuItem_becas);

        jMenuItem_constancias.setText("Constancias");
        jMenu_tramites.add(jMenuItem_constancias);

        jMenuBar1.add(jMenu_tramites);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("LobosConect");

        jMenuItem_correo.setText("Correo");
        jMenu4.add(jMenuItem_correo);

        jMenuItem_navega.setText("Navegar");
        jMenu4.add(jMenuItem_navega);

        jMenuItem_soporte.setText("Soporte");
        jMenu4.add(jMenuItem_soporte);

        jMenuBar1.add(jMenu4);

        jMenu_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_cerrarSesion.setText("Cerrar sesión");
        jMenuBar1.add(jMenu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_pagoTarjeta)
                    .addComponent(rd_pagoCreditoUT)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipoPago_loboleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(btn_pagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_vencimientoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pass_cve))
                            .addComponent(txt_numTarjeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tBtn_tecladoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tBtn_tecladoCVE, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_vencimientoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipoPago_loboleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(rd_pagoCreditoUT)
                        .addGap(3, 3, 3)
                        .addComponent(rd_pagoTarjeta)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tBtn_tecladoTarjeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass_cve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tBtn_tecladoCVE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_vencimientoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cb_vencimientoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pagar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teclado_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclado_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclado_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_pagar;
    public javax.swing.JComboBox<String> cb_tipoPago;
    public javax.swing.JComboBox<String> cb_tipoPago_loboleto;
    public javax.swing.JComboBox<String> cb_vencimientoAnio;
    public javax.swing.JComboBox<String> cb_vencimientoMes;
    public javax.swing.JFrame frame_servTeclado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem_ConsMapa;
    public javax.swing.JMenuItem jMenuItem_becas;
    public javax.swing.JMenuItem jMenuItem_calendario;
    public javax.swing.JMenuItem jMenuItem_consCalificaciones;
    public javax.swing.JMenuItem jMenuItem_consEdoCuenta;
    public javax.swing.JMenuItem jMenuItem_consHorario;
    public javax.swing.JMenuItem jMenuItem_constancias;
    public javax.swing.JMenuItem jMenuItem_correo;
    public javax.swing.JMenuItem jMenuItem_navega;
    public javax.swing.JMenuItem jMenuItem_servBuzon;
    public javax.swing.JMenuItem jMenuItem_servCaja;
    public javax.swing.JMenuItem jMenuItem_servCreditoUT;
    public javax.swing.JMenuItem jMenuItem_servEvaluacion;
    public javax.swing.JMenuItem jMenuItem_servLoboletos;
    public javax.swing.JMenuItem jMenuItem_soporte;
    public javax.swing.JMenu jMenu_cerrarSesion;
    private javax.swing.JMenu jMenu_servCaja;
    public javax.swing.JMenu jMenu_tramites;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPasswordField pass_cve;
    private javax.swing.ButtonGroup radioGroup_formaPago;
    public javax.swing.JRadioButton rd_pagoCreditoUT;
    public javax.swing.JRadioButton rd_pagoTarjeta;
    public javax.swing.JToggleButton tBtn_tecladoCVE;
    public javax.swing.JToggleButton tBtn_tecladoTarjeta;
    public javax.swing.JButton teclado_btn0;
    public javax.swing.JButton teclado_btn1;
    public javax.swing.JButton teclado_btn2;
    public javax.swing.JButton teclado_btn3;
    public javax.swing.JButton teclado_btn4;
    public javax.swing.JButton teclado_btn5;
    public javax.swing.JButton teclado_btn6;
    public javax.swing.JButton teclado_btn7;
    public javax.swing.JButton teclado_btn8;
    public javax.swing.JButton teclado_btn9;
    public javax.swing.JButton teclado_btnAceptar;
    public javax.swing.JButton teclado_btnAtras;
    public javax.swing.JButton teclado_btnLimpiar;
    public javax.swing.JTextArea txtArea_recibo;
    public javax.swing.JTextField txt_numTarjeta;
    // End of variables declaration//GEN-END:variables
}
