/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class ServSoporte extends javax.swing.JFrame {

    /**
     * Creates new form ServSoporte
     */
    public ServSoporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_mensajeSoporte = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_soporte = new javax.swing.JTextArea();
        btn_enviarSoporte = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_servCaja = new javax.swing.JMenu();
        jMenuItem_servCaja = new javax.swing.JMenuItem();
        jMenuItem_servCreditoUT = new javax.swing.JMenuItem();
        jMenuItem_servLoboletos = new javax.swing.JMenuItem();
        jMenuItem_servEvaluacion = new javax.swing.JMenuItem();
        jMenuItem_servBuzon = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_consCalificaciones = new javax.swing.JMenuItem();
        jMenuItem_consHorario = new javax.swing.JMenuItem();
        jMenuItem_consEdoCuenta = new javax.swing.JMenuItem();
        jMenuItem_ConsMapa = new javax.swing.JMenuItem();
        jMenuItem_calendario = new javax.swing.JMenuItem();
        jMenu_tramites = new javax.swing.JMenu();
        jMenuItem_becas = new javax.swing.JMenuItem();
        jMenuItem_constancias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_correo = new javax.swing.JMenuItem();
        jMenuItem_navega = new javax.swing.JMenuItem();
        jMenuItem_soporte = new javax.swing.JMenuItem();
        jMenu_cerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_mensajeSoporte.setText("¿Tienes algún problema con CajeroUT?");

        jLabel2.setText("Mandanos un mensaje para atenderlo a la brevedad:");

        txtArea_soporte.setColumns(20);
        txtArea_soporte.setRows(5);
        jScrollPane1.setViewportView(txtArea_soporte);

        btn_enviarSoporte.setText("Enviar");

        jMenuBar1.setBackground(new java.awt.Color(6, 12, 60));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu_servCaja.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_servCaja.setText("Servicios");

        jMenuItem_servCaja.setText("Caja");
        jMenu_servCaja.add(jMenuItem_servCaja);

        jMenuItem_servCreditoUT.setText("CreditoUT");
        jMenu_servCaja.add(jMenuItem_servCreditoUT);

        jMenuItem_servLoboletos.setText("Loboletos");
        jMenu_servCaja.add(jMenuItem_servLoboletos);

        jMenuItem_servEvaluacion.setText("Evaluación de servicios");
        jMenu_servCaja.add(jMenuItem_servEvaluacion);

        jMenuItem_servBuzon.setText("Buzón de quejas y sugerencias");
        jMenu_servCaja.add(jMenuItem_servBuzon);

        jMenuBar1.add(jMenu_servCaja);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Consultas");

        jMenuItem_consCalificaciones.setText("Calificaciones");
        jMenu2.add(jMenuItem_consCalificaciones);

        jMenuItem_consHorario.setText("Horario");
        jMenu2.add(jMenuItem_consHorario);

        jMenuItem_consEdoCuenta.setText("Estado de cuenta");
        jMenu2.add(jMenuItem_consEdoCuenta);

        jMenuItem_ConsMapa.setText("Mapa Universidad");
        jMenu2.add(jMenuItem_ConsMapa);

        jMenuItem_calendario.setText("Calendario");
        jMenu2.add(jMenuItem_calendario);

        jMenuBar1.add(jMenu2);

        jMenu_tramites.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_tramites.setText("Trámites");

        jMenuItem_becas.setText("Becas");
        jMenu_tramites.add(jMenuItem_becas);

        jMenuItem_constancias.setText("Constancias");
        jMenu_tramites.add(jMenuItem_constancias);

        jMenuBar1.add(jMenu_tramites);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("LobosConect");

        jMenuItem_correo.setText("Correo");
        jMenu4.add(jMenuItem_correo);

        jMenuItem_navega.setText("Navegar");
        jMenu4.add(jMenuItem_navega);

        jMenuItem_soporte.setText("Soporte");
        jMenu4.add(jMenuItem_soporte);

        jMenuBar1.add(jMenu4);

        jMenu_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_cerrarSesion.setText("Cerrar sesión");
        jMenuBar1.add(jMenu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mensajeSoporte)
                            .addComponent(jLabel2))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_enviarSoporte)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_mensajeSoporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_enviarSoporte)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServSoporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_enviarSoporte;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem_ConsMapa;
    public javax.swing.JMenuItem jMenuItem_becas;
    public javax.swing.JMenuItem jMenuItem_calendario;
    public javax.swing.JMenuItem jMenuItem_consCalificaciones;
    public javax.swing.JMenuItem jMenuItem_consEdoCuenta;
    public javax.swing.JMenuItem jMenuItem_consHorario;
    public javax.swing.JMenuItem jMenuItem_constancias;
    public javax.swing.JMenuItem jMenuItem_correo;
    public javax.swing.JMenuItem jMenuItem_navega;
    public javax.swing.JMenuItem jMenuItem_servBuzon;
    public javax.swing.JMenuItem jMenuItem_servCaja;
    public javax.swing.JMenuItem jMenuItem_servCreditoUT;
    public javax.swing.JMenuItem jMenuItem_servEvaluacion;
    public javax.swing.JMenuItem jMenuItem_servLoboletos;
    public javax.swing.JMenuItem jMenuItem_soporte;
    public javax.swing.JMenu jMenu_cerrarSesion;
    private javax.swing.JMenu jMenu_servCaja;
    public javax.swing.JMenu jMenu_tramites;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_mensajeSoporte;
    public javax.swing.JTextArea txtArea_soporte;
    // End of variables declaration//GEN-END:variables
}
